### ISSUE TITLE
Crashes on connect

### ISSUE THREAD

**Issue by AgitationSkeleton** [WatermelonMojito/bta-utils-melon#3]
2024-03-25 12:07:37 ERROR Minecraft - Unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class de.olivermakesco.bta_discord_integration.server.DiscordChatRelay
	at net.minecraft.server.net.handler.NetLoginHandler.handler$zzb000$bta_utils$sendJoinMessage(NetLoginHandler.java:527)
	at net.minecraft.server.net.handler.NetLoginHandler.doLogin(NetLoginHandler.java:158)
	at net.minecraft.server.net.handler.NetLoginHandler.tryLogin(NetLoginHandler.java:59)
	at net.minecraft.server.net.NetworkListenThread.handleNetworkListenThread(NetworkListenThread.java:78)
	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:588)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.net.thread.ThreadServerApplication.run(ThreadServerApplication.java:21)

**Comment by elisttm** [comment]
i am also having this issue

```
java.lang.NoClassDefFoundError: Could not initialize class de.olivermakesco.bta_discord_integration.server.DiscordChatRelay
        at net.minecraft.server.net.handler.NetLoginHandler.handler$zzb000$bta_utils$sendJoinMessage(NetLoginHandler.java:527)
        at net.minecraft.server.net.handler.NetLoginHandler.doLogin(NetLoginHandler.java:154)
        at net.minecraft.server.net.handler.NetLoginHandler.tryLogin(NetLoginHandler.java:55)
        at net.minecraft.server.net.NetworkListenThread.handleNetworkListenThread(NetworkListenThread.java:74)
        at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
        at net.minecraft.server.net.thread.ThreadServerApplication.run(ThreadServerApplication.java:17)
```
